---
- name: copy_file_from_server
  hosts: db_server
  tasks:

    - name: copy ssms from server to win_node
      win_copy:
        src: Z:\SSMS-Setup.exe
        dest: C:\Temp\
        remote_src: yes
                
    - name: copy config_csv_file by powershell from server to temp
      win_shell: C:\Temp\copyConfigcsvFile.ps1 
                
    - name: update config_ini_file by powershell 
      win_shell: C:\Temp\updateSQLServerConfigFile.ps1
