---
- name: copy_from_lnx_and_move_files
  hosts: db_server
  tasks:

    - name: create directory 'D:\Temp' on target server
      win_file:
        path: C:\Temp
        state: directory

    - name: copy file from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/create_db.yml 
        dest: C:\TEMP\
        
    - name: copy powershellfile copyconfig from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/copyConfigcsvFile.ps1
        dest: C:\TEMP\
        
    - name: copy powershellfile updatesqlini from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/updateSQLServerConfigFile.ps1
        dest: C:\TEMP\        
        
    - name: copy cfg_ini_file from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/cfg.ini 
        dest: C:\TEMP\   

    - name: copy ssms_install_ps1 from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/install_ssms.ps1 
        dest: C:\TEMP\   

    - name: copy ssms_install_yml from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/install_ssms.yml 
        dest: C:\TEMP\   

    - name: copy reboot_server from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/reboot_server.yml 
        dest: C:\TEMP\   

    - name: copy delte_temp_directory from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/delete_temp_directory.yml 
        dest: C:\TEMP\   
