---
- name: install sql_server
  hosts: 192.168.0.21
  tasks:

    - name: create directory 'D:\Temp' on target server
      win_file:
        path: C:\Temp
        state: directory

    - name: copy sql_zip_file from server to node and unzip
      win_unzip:
        src: Z:\SQL2019.zip
        dest: C:\TEMP\
        delete_archive: no 

    - name: copy ssms from server to win_node
      win_copy:
        src: Z:\SSMS-Setup.exe
        dest: C:\Temp
        remote_src: yes
   
    - name: copy sql_config_file from lnx to win_node
      win_copy:
        src: Z:\hello.txt
        dest: C:\Temp\
        remote_src: yes


#  - name: install sql server
#    ansible.windows.win_package:
#      path: C:\TEMP\SQL2019\setup.exe
#      ameirguments: ' /ConfigurationFile=C:\TEMP\cfg.ini /q /IAcceptSQLServerLicenseTerms'
#      state: present

