---
- name: install sql_server
  hosts: db_server
  tasks:

    - name: create directory 'D:\Temp' on target server
      win_file:
        path: C:\Temp
        state: directory

    - name: copy file from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/install_sql.yml 
        dest: C:\TEMP\
        
    - name: copy powershellfile copyconfig from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/copyConfigcsvFile.ps1
        dest: C:\TEMP\
        
    - name: copy powershellfile updatesqlini from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/updateSQLServerConfigFile.ps1
        dest: C:\TEMP\        
        
    - name: copy cfg_ini_file from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/cfg.ini 
        dest: C:\TEMP\   
