---
- name: install sql_server
  hosts: db_server
  tasks:

    - name: create directory 'D:\Temp' on target server
      win_file:
        path: C:\Temp
        state: directory

    - name: copy file from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/install_sql.yml 
        dest: C:\TEMP\
        
    - name: copy powershellfile copyconfig from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/copyConfigcsvFile.ps1
        dest: C:\TEMP\
        
    - name: copy powershellfile updatesqlini from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/updateSQLServerConfigFile.ps1
        dest: C:\TEMP\        
        
    - name: copy cfg_ini_file from lnx to win
      win_copy: 
        src: /var/lib/awx/projects/_8__sql_install/cfg.ini 
        dest: C:\TEMP\   
        
    - name: copy sql_zip_file from server to node and unzip
      win_unzip:
        src: Z:\SQL2019.zip
        dest: C:\TEMP\
        delete_archive: no 

    - name: copy ssms from server to win_node
      win_copy:
        src: Z:\SSMS-Setup.exe
        dest: C:\Temp\
        remote_src: yes
                
    - name: copy config_csv_file by powershell from server to temp
      win_shell: C:\Temp\copyConfigcsvFile.ps1 
                
    - name: update config_ini_file by powershell 
      win_shell: C:\Temp\updateSQLServerConfigFile.ps1 
        
    - name: copy sql_config_file from lnx to win_node
      win_copy:
        src: Z:\hello.txt
        dest: C:\Temp\
        remote_src: yes


#  - name: install sql server
#    ansible.windows.win_package:
#      path: C:\TEMP\SQL2019\setup.exe
#      ameirguments: ' /ConfigurationFile=C:\TEMP\cfg.ini /q /IAcceptSQLServerLicenseTerms'
#      state: present

